USE TinyHouseDB;
GO

CREATE TABLE Reviews (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  HouseId INT NOT NULL REFERENCES Houses(Id),
  UserId INT NOT NULL REFERENCES Users(Id),
  Rating INT NOT NULL CHECK (Rating BETWEEN 1 AND 5),
  Text NVARCHAR(MAX) NULL,
  CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);